# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Check out code repository source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Run build
        run: yarn build

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # Fetch tags and describe the commit before the merge commit
      # to see if it's a version publish
      - name: Publish
        run: |
          git fetch --tags
          if git describe --exact-match --match "v*.*.*" HEAD^2
          then
            echo "Found version commit tag. Publishing."
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
            yarn install
            yarn build
            npm publish
          else
            echo "Version commit tag not found. Not publishing."
          fi